apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:  # describes how every pod should behave
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ticketing/client
          env:
          - name: STRIPE_PUBLISHABLE_KEY
            value: pk_test_51LAuXwHNnWD8te6dRHGnjiU0rFVHCg5OvtGzsmMJt5BpbDDj70XSCoD70o88QCGr8oMS1LAuBH1BEFoHzJfDmFoS002DQWrBqg
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector: # how the service would find the deployment component
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
